# Generated by Django 2.1.5 on 2019-02-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
    ]
