# Generated by Django 2.1.5 on 2019-02-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190211_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/logo.png', null=True, upload_to='profile_picture'),
        ),
    ]
