# Generated by Django 2.1.5 on 2019-02-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190214_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='slug',
            field=models.SlugField(default=0, help_text="Slug will be generated automatically from the user's username", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated automatically from the title of the post', unique=True),
        ),
    ]
