# Generated by Django 2.1.5 on 2019-02-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190215_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='bio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
