# Generated by Django 2.1.5 on 2019-02-17 13:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190216_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='logo.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='logo.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
